# DMI calculation from total energy
## Linear monoatomic chain

In [13]:
from utils import *
np.set_printoptions(precision=3, suppress=True)

Define the 
* spin spirals calculated by DFT and 
* the maximum number of nearest-neighbors considered

In [14]:
# spin spirals (DFT supercells) - sign indicates the chirality: e.g. [-3, 3], or [4, -4], or [-3, 3, 4, 5, 6], order doesn't seem to matter
Ns_array = [4, -4] #[3, -3, 4, 5]

# maximum order of nearest-neighbors; 5 is probably more than enough (physically)
max_d_order = 8    

Construct total energy expressions for all spin spirals (express as a matrix) \
and diagonalize the square submatrix of this rectangular matrix.

In [15]:
M = coeff_matrix(Ns_array, max_d_order=max_d_order)
M_partially_diagonalized, M_sub_inv = diagonalize_coefficient_matrix(M)

In [16]:
print("with DFT supercell sizes")
print(Ns_array)

print('')

print("we obtain linear combinations of terms")
print(['E0'] + [f'd_{n:d}' for n in range(1, max_d_order+1)])

print('')

print('combined in the following way')
print(M_partially_diagonalized)

print('')

print("by summing the energies")
print([f"E({Ns:d})" for Ns in Ns_array])

print('')

print("with prefactor coefficients")
print(M_sub_inv)

with DFT supercell sizes
[3, -3, 4, 5]

we obtain linear combinations of terms
['E0', 'd_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8']

combined in the following way
[[ 1.    -0.    -0.     0.     0.     0.    -0.    -0.     0.   ]
 [ 0.     1.    -0.     0.    -0.382 -1.236  1.     1.854 -1.236]
 [ 0.     0.     1.    -0.    -1.382 -0.236  1.     0.854 -0.236]
 [ 0.    -0.    -0.     1.    -0.382 -2.236  1.     2.854 -1.236]]

by summing the energies
['E(3)', 'E(-3)', 'E(4)', 'E(5)']

with prefactor coefficients
[[ 0.167  0.167 -0.    -0.   ]
 [ 0.047 -0.191 -0.155  0.21 ]
 [-0.146  0.001 -0.155  0.21 ]
 [ 0.213 -0.025 -0.405  0.21 ]]


In [17]:
explain_results_verbose(M_sub_inv, M_partially_diagonalized, Ns_array)

Having calculated the DFT total energies for supercells (3, -3, 4, 5), corresponding to angles (120.0, -120.0, 90.0, 72.0) degrees, 
                we obtain the ground-state energy E0 and the DMI coefficients d_n up to order n_max = 8
                  with the following formulas:
E0 = 0.167 E(3) + 0.167 E(-3)
1.000 d_1 + -0.382 d_4 + -1.236 d_5 + 1.000 d_6 + 1.854 d_7 + -1.236 d_8 = 0.047 E(3) + -0.191 E(-3) + -0.155 E(4) + 0.210 E(5)
1.000 d_2 + -1.382 d_4 + -0.236 d_5 + 1.000 d_6 + 0.854 d_7 + -0.236 d_8 = -0.146 E(3) + 0.001 E(-3) + -0.155 E(4) + 0.210 E(5)
1.000 d_3 + -0.382 d_4 + -2.236 d_5 + 1.000 d_6 + 2.854 d_7 + -1.236 d_8 = 0.213 E(3) + -0.025 E(-3) + -0.405 E(4) + 0.210 E(5)
